# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: cd
      run: cd RunLengthEncoding
    - name: ls
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build RunLengthEncoding/RunLengthEncoding.sln --no-restore
    - name: Test
      run: dotnet test RunLengthEncoding/RunLengthEncoding.sln --no-build --verbosity normal
